/*------------------------------------------------------------------------------------------------*/
/* Author: Alfred Gerke (AGE)                                                  
/* Date: 2019-02-22                                                        
/* Description: Es wird das Model für Settings angelegt       
/*                                                                              
/*------------------------------------------------------------------------------------------------*/
/* - Das Script arbeitet mit Befehlen der SQL-Erweiterung für FB 3.0x   
/* - Das Script ist für die Ausführung im ISQL erstellt worden
/* - Ein Datenbank-Connect wird vorausgesetzt
/*   
/*------------------------------------------------------------------------------------------------*/
/* History: 2019-02-22
/*          Script erstellen
/*   
/*------------------------------------------------------------------------------------------------*/

/* ---------------------------------------------------------------------------------------------- */
CREATE GLOBAL TEMPORARY TABLE TBT_SETTING (
  ID DN_IDENTIFICATION generated by default as identity primary key,
  CATEGORY_NAME DN_CATEGORY NOT NULL,
  SECTION_NAME  DN_CATEGORY_SECTION NOT NULL,
  IDENT         DN_CATEGORY_IDENT NOT NULL,
  STRING_VALUE  DN_CATEGORY_STRING_VALUE NOT NULL
)
on commit delete rows;

COMMENT ON TABLE TBT_SETTING 
IS 'Temporäre Datenbank INI-Datei';

COMMENT ON COLUMN TBT_SETTING.ID
IS 'Primärschlüssel';

COMMENT ON COLUMN TBT_SETTING.CATEGORY_NAME
IS 'Kategorie (vergleichbar mit dem Namen einer Ini-Datei oder einem Registry-Schlüssel)';

COMMENT ON COLUMN TBT_SETTING.SECTION_NAME
IS 'Section (vergleichbar mit einer Ini-Datei)';

COMMENT ON COLUMN TBT_SETTING.IDENT
IS 'Ident (vergleichbar mit einer Ini-Datei)';

COMMENT ON COLUMN TBT_SETTING.STRING_VALUE
IS 'Value (vergleichbar mit einer Ini-Datei)';

/*
  ## Problem mit der Schlüsselgröße
    * s. http://www.firebirdfaq.org/faq211/
    * s. http://www.firebirdfaq.org/ip_ib_indexcalculator.htm
*/
         
ALTER TABLE TBT_SETTING ADD CONSTRAINT UNQ_TBT_SETTING UNIQUE (CATEGORY_NAME, SECTION_NAME, IDENT);

COMMIT WORK;
/* ---------------------------------------------------------------------------------------------- */

CREATE VIEW VW_T_SETTING (
  ID,
  CATEGORY_NAME,
  SECTION_NAME,
  IDENT,
  STRING_VALUE)
AS
select
  ID,
  CATEGORY_NAME,
  SECTION_NAME,
  IDENT,
  STRING_VALUE
from
  TBT_SETTING;

COMMENT ON VIEW VW_T_SETTING 
IS 'Temporäre Standard Update-View für die Tabelle TBT_SETTING';

COMMIT WORK;
/* ---------------------------------------------------------------------------------------------- */

CREATE TABLE TB_SETTING (
  ID DN_IDENTIFICATION generated by default as identity primary key,
  CATEGORY_NAME DN_CATEGORY NOT NULL,
  SECTION_NAME  DN_CATEGORY_SECTION NOT NULL,
  IDENT         DN_CATEGORY_IDENT NOT NULL,
  STRING_VALUE  DN_CATEGORY_STRING_VALUE NOT NULL
);

COMMENT ON TABLE TB_SETTING 
IS 'Datenbank INI-Datei';

COMMENT ON COLUMN TBT_SETTING.ID
IS 'Primärschlüssel';

COMMENT ON COLUMN TBT_SETTING.CATEGORY_NAME
IS 'Kategorie (vergleichbar mit dem Namen einer Ini-Datei oder einem Registry-Schlüssel)';

COMMENT ON COLUMN TB_SETTING.SECTION_NAME
IS 'Section (vergleichbar mit einer Ini-Datei)';

COMMENT ON COLUMN TB_SETTING.IDENT
IS 'Ident (vergleichbar mit einer Ini-Datei)';

COMMENT ON COLUMN TB_SETTING.STRING_VALUE
IS 'Value (vergleichbar mit einer Ini-Datei)';

/*
  ## Problem mit der Schlüsselgröße
    * s. http://www.firebirdfaq.org/faq211/
    * s. http://www.firebirdfaq.org/ip_ib_indexcalculator.htm
*/
         
ALTER TABLE TB_SETTING ADD CONSTRAINT UNQ_TB_SETTING UNIQUE (CATEGORY_NAME, SECTION_NAME, IDENT);

COMMIT WORK;
/* ---------------------------------------------------------------------------------------------- */

CREATE VIEW VW_SETTING (
  ID,
  CATEGORY_NAME,
  SECTION_NAME,
  IDENT,
  STRING_VALUE)
AS
select
  ID,
  CATEGORY_NAME,
  SECTION_NAME,
  IDENT,
  STRING_VALUE
from
  TB_SETTING;

COMMENT ON VIEW VW_SETTING 
IS 'Standard Update-View für die Tabelle TB_SETTING';

COMMIT WORK;
/*------------------------------------------------------------------------------------------------*/
/* Updatehistory                                   
/*------------------------------------------------------------------------------------------------*/

SET TERM ^ ;
EXECUTE BLOCK AS
BEGIN
  execute
  procedure
  PKG_HISTORY.SP_SET_UPDATE_INFO (0,
    0,
    'sddl.bootstrap.create.setting.model.sql',
    'Model für die Settings installiert');
END^        
SET TERM ; ^

COMMIT WORK;
/*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*/