/*------------------------------------------------------------------------------------------------*/
/* Author: Alfred Gerke (AGE)                                                  
/* Date: 2019-07-06                                                      
/* Description: Es wird das Model für das SQL Package angelegt       
/*                                                                              
/*------------------------------------------------------------------------------------------------*/
/* - Das Script arbeitet mit Befehlen der SQL-Erweiterung für FB 3.0x   
/* - Das Script ist für die Ausführung im ISQL erstellt worden
/* - Ein Datenbank-Connect wird vorausgesetzt
/*   
/*------------------------------------------------------------------------------------------------*/
/* History: 2019-07-06
/*          Script erstellen
/*   
/*------------------------------------------------------------------------------------------------*/

/* ---------------------------------------------------------------------------------------------- */
CREATE GLOBAL TEMPORARY TABLE TBT_SQL_STATEMENT (
  ID DN_IDENTIFICATION generated by default as identity primary key,
  SQL_IDENT DN_SQL_IDENT,
  SQL_STATEMENT DN_SQL_STMT
)
on commit delete rows;

COMMENT ON TABLE TBT_SQL_STATEMENT 
IS 'Temporäre Tabelle zum Zusammenstellen eines umfangreichen SQL_STATEMENTS';

COMMENT ON COLUMN TBT_SQL_STATEMENT.ID
IS 'Primärschlüssel';

COMMENT ON COLUMN TBT_SQL_STATEMENT.SQL_IDENT
IS 'Identifizierung für ein Script';

COMMENT ON COLUMN TBT_SQL_STATEMENT.SQL_STATEMENT
IS 'Umfangreiches SQL-Stamtent';

CREATE UNIQUE INDEX UNQ_IDX_SQL_IDENT ON TBT_SQL_STATEMENT (SQL_IDENT);

COMMIT WORK;
/* ---------------------------------------------------------------------------------------------- */

CREATE VIEW VW_T_SQL_STATEMENT (
  ID,
  SQL_IDENT,
  SQL_STATEMENT)
AS
select
  ID,
  SQL_IDENT,
  SQL_STATEMENT
from
  TBT_SQL_STATEMENT;

COMMENT ON VIEW VW_T_SQL_STATEMENT 
IS 'Temporäre Standard Update-View für die Tabelle TBT_SQL_STATEMENT';

COMMIT WORK;
/*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*/